### PR TITLE
V0.2 Admin Login + CSS

### PR DESCRIPTION
**Pull request by SamHarbi**
Moved PHP to another file

### CODE REVIEW

**Comment by DragonBrooksy** [comment]
All good, just a template for now though

**Comment by ScottyDog5** [comment]
All of it looks good

**Comment by DanielJakubek** [comment]
It would be a good idea to make a master style sheet instead of each page of ours using different ones.

**Comment by SamHarbi** [comment]
Yep! that sounds good, once we get that style sheet we could delete this one

**Pull request merged**
