### PR TITLE
The index page with it's css and js

### PR DESCRIPTION
**Pull request by DanielJakubek**
The index page and all its glory.

### CODE REVIEW

**Comment by DragonBrooksy** [comment]
Looks good to me, need to make the rest of the pages reliant on the master css page.

**Comment by Gregor-Davis** [comment]
Index page looks good so far.

**Comment by SamHarbi** [comment]
Looking great

**Review by SamHarbi — APPROVED** [review]
All looks good

**Comment by ScottyDog5** [comment]
Looks good

**Pull request merged**
