### PR TITLE
Build 2.1

### PR DESCRIPTION
**Pull request by DanielJakubek**
This is the system after sprint 2.

### CODE REVIEW

**Review by DragonBrooksy — APPROVED** [review]
All good!

**Review by Gregor-Davis — APPROVED** [review]
Many improvements over the course of the sprint, functions as intended

**Review by ScottyDog5 — COMMENTED** [review]
A good starting point for sprint 3

**Review by alecavi — APPROVED** [review]
Looks good

**Review by ScottyDog5 — APPROVED** [review]

**Review by SamHarbi — APPROVED** [review]
Looks good, Good job everyone!

**Pull request merged**
