### PR TITLE
Refactor Update

### LINKED ISSUE #14: As an admin, I want to be able to change information on the website so that it is kept up to date.
Definition of Done:

- [x] The implementation is hosted on the web server.
- [x] The code follows camelCase.
- [x] The page layout is comprehensive.
- [x] There are no real graphical issues or bugs present.
- [x] Code reviewed by peer.
- [x] Accepted by product owner.
- [x] The code is commented to an acceptable level.
- [x] Subtasks have been completed.

TODO
- [x] Create a dashboard of buttons to edit pages
- [x] Have an ability to select every page
- [x] Have an ability to edit divs that contain content / non design template elements
- [x] Implement the edit

### PR DESCRIPTION
**Pull request by SamHarbi**
Cleaned up the code to hit all DODs which included:
-Adding Comments 
-Fixing a small bug in the php logic
close #14

### CODE REVIEW

**Review by DanielJakubek — APPROVED** [review]
Looks good! Love that you also added the bug label and fixed the bug. Will merge now.

**Review by alecavi — APPROVED** [review]
looks good

**Review by Gregor-Davis — APPROVED** [review]
Looks good to me

**Review by ScottyDog5 — COMMENTED** [review]
The comments make it easier to understand, looks good to merge

**Pull request merged**
