### PR TITLE
Admin Dashboard Complete

### LINKED ISSUE #16: As an admin, I want to be able to add multiple users to the system, so that others can also alter the website.
Definition of Done:

- [x] The implementation is hosted on the web server.
- [x] The code follows camelCase.
- [x] The page layout is comprehensive.
- [x] There are no real graphical issues or bugs present.
- [x] Code reviewed by peer.
- [x] Accepted by product owner.
- [x] The code is commented to an acceptable level.
- [x] Subtasks have been completed,
- [x] The page is responsive enough to give the user a good mobile experience.

Tasks to do:

- [x] Add buttons to input information.
- [x] Add the information to the database.
- [x] Allow the new user to log in.

### LINKED ISSUE #17: As an Admin, I want only authorised users to be able to update the website, so that a malicious actor cannot create an unauthorised change.
Definition of Done:

- [x] The implementation is hosted on the web server.
- [x] The code follows camelCase.
- [x] There are no real graphical issues or bugs present.
- [x] Code reviews by peer.
- [x] Reviewed by product owner.
- [x] The code is commented to an acceptable level.
- [x] Subtasks have been completed.

Tasks to do:

- [x] Track if user is logged in.
- [x] Block access to admin activities if not logged in.

### PR DESCRIPTION
**Pull request by SamHarbi**
Added the ability to create new admins, created a full layout for the admin dashboard, made it visible on mobile, made it so only admins have the ability to perform the actions.

#close 16
#close 17

### CODE REVIEW

**Review by DanielJakubek — APPROVED** [review]
Looks like no more conflicts, ready to merge.

**Comment by Gregor-Davis** [comment]
Looks good, don't see any issues

**Review by Gregor-Davis — APPROVED** [review]
No conflicts, looks good

**Comment by ScottyDog5** [comment]
Looks good to merge, no conflicts. Always good to see camel case

**Pull request merged**
