### PR TITLE
Story7 items

### PR DESCRIPTION
**Pull request by DanielJakubek**
Story 7 has been completed along with all its subtasks.
Also fixed some issues with the map and updated goal pages to be up to date.

#7  #62

### CODE REVIEW

**Review by ScottyDog5 — COMMENTED** [review]
All looks good to merge

**Review by Gregor-Davis — COMMENTED** [review]
Looks good, can't see any issues with it

**Review by DragonBrooksy — COMMENTED** [review]
Looks good! Just need to make the finishing touches.

**Review by DragonBrooksy — APPROVED** [review]

**Review by alecavi — APPROVED** [review]
Looks good.

**Review by SamHarbi — APPROVED** [review]
Looks good

**Pull request merged**
