### PR TITLE
Cleaning up software code

### PR DESCRIPTION
**Pull request by DanielJakubek**
Cleaned up the directories so that it is easier to read and comprehend.

### CODE REVIEW

**Comment by Gregor-Davis** [comment]
Looks much better!

**Comment by ScottyDog5** [comment]
All looks good, should be easier to work with now

**Comment by alecavi** [comment]
Agreed, this is a significant improvement

**Review by DragonBrooksy — APPROVED** [review]
Makes the GitHub look a lot cleaner!

**Review by SamHarbi — APPROVED** [review]
Looks good

**Pull request merged**
